# Generated by Django 4.2.7 on 2024-01-11 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_created_blog_title_tag_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 11, 6, 50, 603882)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_tag',
            field=models.CharField(max_length=350),
        ),
    ]
